### PR TITLE
0.5.4

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@hroncok I know gast release are always a bit touchy, this one should only catch up with python 3.11 constructs... Can you give me your green light from Fedora point of view? I'll trigger updates of beniget and pythran in the forthcoming weeks...

**Comment by hroncok** [comment]
Will check.

**Comment by serge-sans-paille** [comment]
@hroncok good to go?

**Comment by hroncok** [comment]
I am so sorry, this has been lurking on my TODO list but I wasn't able to dedicate the time :/

**Pull request merged**
