### PR TITLE
Add the test suite to the release tarball

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Thanks for the proposed change. I don't always shipt tests in the tarball, to make DL lighter. I guess It's not a big issue for ``gast`` as the tests are small... Why are you missing these tests?

**Comment by serge-sans-paille** [comment]
Great news! I'm no longer very active in debian-science, glad to read that.

I'm ok to bundle the tests, and yes there are several packaging choices made for pythran that seems relevant for pip but not for debian, I'll happily discuss/patch the codebase so that integration is easier.

**Comment by ghisvail** [comment]
> Great news! I'm no longer very active in debian-science, glad to read that.

`pythran` will be officially maintained by the DST anyway, so you would still have a chance to directly commit to the packaging repository.

>  I'll happily discuss/patch the codebase so that integration is easier

For a start, we'd need to make sure `pythran` can be built with the packaged sources in `libboost-dev` instead of the vendored copy (which will be stripped from the release tarball).

> I'm ok to bundle the tests

I would need the same for `pythran`. For the latter, you should probably just add an `__init__.py` file under `pythran/tests` and discover packages via setuptools' `find_package`. No need for a separate MANIFEST.in file then.

**Comment by serge-sans-paille** [comment]
> For a start, we'd need to make sure `pythran` can be built with the packaged sources in `libboost-dev` instead of the vendored copy (which will be stripped from the release tarball).

I can provide a setup.py flag to use system boost instead of the
vendored copy, if that's easier.

> > I'm ok to bundle the tests
> 
> I would need the same for `pythran`. For the latter, you should probably just add an `__init__.py` file under `pythran/tests` and discover packages via setuptools' `find_package`. No need for a separate MANIFEST.in file then.

Will do!

**Comment by ghisvail** [comment]
> I can provide a setup.py flag to use system boost instead of the vendored copy, if that's easier.

Or I can just symlink at the appropriate location expected by `pythran`. After that, does `pythran` still needs the boost sources somewhere in its package path when installed?

**Comment by ghisvail** [comment]
@serge-sans-paille Could you make a new upload to PyPI with the tests included, please?

**Comment by serge-sans-paille** [comment]
done!

i've also added a pythran PR to fix boost deployement, tell me when
you're okay with that too.

**Pull request merged**
